[project]
name = "agenda-bloco-api"
version = "0.1.0"
description = "API do Agenda de Blocos"
requires-python = ">=3.10"

dependencies = [
  "fastapi==0.111.0",
  "uvicorn[standard]==0.30.1",
  "pydantic-settings==2.2.1"
]

[tool.uvicorn]
app = "src.main:app"
